# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded tdao 0.1.1 [list source [file join $dir tdao.tcl]]
package ifneeded tdao::dao 0.1.1 [list source [file join $dir dao.tcl]]
package ifneeded tdao::dbc 0.1.1 [list source [file join $dir dbc.tcl]]
package ifneeded tdao::dbc::mariadb 0.1.1 [list source [file join $dir mariadb.tcl]]
package ifneeded tdao::dbc::postgres 0.1.1 [list source [file join $dir postgress.tcl]]
package ifneeded tdao::dbc::sqlite 0.1.1 [list source [file join $dir sqlite.tcl]]
